import { generatePassword, sha256 } from './security';

export type WordPressSeed = { files: Record<string, string>; adminUsername: string; adminPassword: string; databaseUsername: string; databasePassword: string };

export async function createWordPressSeed(slug: string, adminEmail: string): Promise<WordPressSeed> {
  const adminPassword = generatePassword();
  const databasePassword = generatePassword();
  const adminHash = await sha256(adminPassword);
  const now = new Date().toISOString();
  const sqliteSchema = buildSqliteSeed({ slug, adminEmail, adminHash, now });
  return { adminUsername: 'admin_' + slug.replace(/[^a-z0-9]/gi, '').slice(0, 10), adminPassword, databaseUsername: 'db_' + slug.replace(/[^a-z0-9]/gi, '').slice(0, 10), databasePassword, files: { 'wp-admin/index.html': wpAdminHtml(slug), 'wp-content/themes/twentytwentyfour/style.css': themeCss(), 'wp-content/plugins/hello.php': '<?php /* CloudPress compatibility placeholder. */', 'wp-content/database/schema.sql': sqliteSchema, 'worker/index.js': workerTemplate(slug), 'worker/wrangler.toml': workerWrangler(slug), '.github/workflows/deploy.yml': deployWorkflow() } };
}

function buildSqliteSeed(input: { slug: string; adminEmail: string; adminHash: string; now: string }) {
  return `CREATE TABLE wp_posts (ID INTEGER PRIMARY KEY, post_author INTEGER, post_date TEXT, post_content TEXT, post_title TEXT, post_status TEXT, post_name TEXT, post_type TEXT);\nCREATE TABLE wp_options (option_id INTEGER PRIMARY KEY, option_name TEXT UNIQUE, option_value TEXT, autoload TEXT);\nCREATE TABLE wp_users (ID INTEGER PRIMARY KEY, user_login TEXT, user_pass TEXT, user_email TEXT, user_registered TEXT, display_name TEXT);\nCREATE TABLE wp_postmeta (meta_id INTEGER PRIMARY KEY, post_id INTEGER, meta_key TEXT, meta_value TEXT);\nCREATE TABLE wp_terms (term_id INTEGER PRIMARY KEY, name TEXT, slug TEXT, term_group INTEGER);\nCREATE TABLE wp_term_taxonomy (term_taxonomy_id INTEGER PRIMARY KEY, term_id INTEGER, taxonomy TEXT, description TEXT, parent INTEGER, count INTEGER);\nCREATE TABLE wp_term_relationships (object_id INTEGER, term_taxonomy_id INTEGER, term_order INTEGER);\nCREATE TABLE wp_comments (comment_ID INTEGER PRIMARY KEY, comment_post_ID INTEGER, comment_author TEXT, comment_author_email TEXT, comment_content TEXT, comment_approved TEXT, comment_date TEXT);\nCREATE TABLE wp_commentmeta (meta_id INTEGER PRIMARY KEY, comment_id INTEGER, meta_key TEXT, meta_value TEXT);\nCREATE TABLE wp_usermeta (umeta_id INTEGER PRIMARY KEY, user_id INTEGER, meta_key TEXT, meta_value TEXT);\nCREATE TABLE wp_links (link_id INTEGER PRIMARY KEY, link_url TEXT, link_name TEXT);\nINSERT INTO wp_options(option_name, option_value, autoload) VALUES ('siteurl','https://${input.slug}.workers.dev','yes'),('home','https://${input.slug}.workers.dev','yes'),('blogname','${input.slug}','yes'),('admin_email','${input.adminEmail}','yes');\nINSERT INTO wp_users(ID,user_login,user_pass,user_email,user_registered,display_name) VALUES (1,'admin','${input.adminHash}','${input.adminEmail}','${input.now}','CloudPress Admin');\nINSERT INTO wp_usermeta(user_id,meta_key,meta_value) VALUES (1,'wp_capabilities','a:1:{s:13:"administrator";b:1;}'),(1,'wp_user_level','10');\nINSERT INTO wp_posts(ID,post_author,post_date,post_content,post_title,post_status,post_name,post_type) VALUES (1,1,'${input.now}','CloudPress 서버리스 워드프레스형 호스팅이 준비되었습니다.','Hello CloudPress','publish','hello-cloudpress','post');`;
}
function wpAdminHtml(slug: string) { return `<!doctype html><html><head><title>${slug} wp-admin</title></head><body><div id="root">CloudPress wp-admin</div></body></html>`; }
function themeCss() { return 'body{font-family:system-ui,sans-serif;margin:0;color:#191f28}'; }
function workerWrangler(slug: string) { return `name = "${slug}"\nmain = "index.js"\ncompatibility_date = "2026-06-13"\n`; }
function deployWorkflow() { return `name: Deploy Worker\non: [push]\njobs:\n  deploy:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: cloudflare/wrangler-action@v3\n        with:\n          apiToken: \${{ secrets.CLOUDFLARE_API_TOKEN }}\n          workingDirectory: worker\n`; }
function workerTemplate(slug: string) { return `export default { async fetch(request) { const url = new URL(request.url); if (url.pathname === '/bridge.js') return new Response("console.log('CloudPress bridge: ${slug}')", { headers: { 'content-type': 'application/javascript' } }); if (url.pathname.startsWith('/wp-admin/database')) return new Response('<h1>CloudPress phpMyAdmin-compatible SQLite UI</h1>', { headers: { 'content-type': 'text/html;charset=utf-8' } }); if (url.pathname.startsWith('/wp-admin/files')) return new Response('<h1>CloudPress file manager</h1>', { headers: { 'content-type': 'text/html;charset=utf-8' } }); return new Response('<h1>${slug}</h1><p>Serverless WordPress-compatible site on Cloudflare Workers.</p>', { headers: { 'content-type': 'text/html;charset=utf-8', 'cache-control': 'public, max-age=60' } }); } }`; }
