name = "cloudpress"
main = "./dist/_worker.js"
compatibility_date = "2026-06-13"

[[d1_databases]]
binding = "DB"
database_name = "cloudpress"
database_id = "local-cloudpress"

[[kv_namespaces]]
binding = "KV"
id = "local-cloudpress-kv"
